export const COMMANDCODE_BASE_URL = "https://api.commandcode.ai/provider/v1"

export const COMMANDCODE_VARIANTS: Record<string, Record<string, unknown>> = {
  default: {},
  low: { reasoningEffort: "low" },
  medium: { reasoningEffort: "medium" },
  high: { reasoningEffort: "high" },
  xhigh: { reasoningEffort: "xhigh" },
  max: { reasoningEffort: "max" },
}

export type CommandCodeModelDefinition = {
  id: string
  name: string
  family: string
  context: number
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  image?: boolean
}

// This is the CommandCode catalog at the time this fork was frozen. The IDs
// are the official provider IDs, not display-name aliases, so the same list
// works with both the OpenAI-compatible API and the CommandCode CLI.
export const COMMANDCODE_MODELS: CommandCodeModelDefinition[] = [
  {
    id: "poolside/laguna-s-2.1-free",
    name: "Laguna S 2.1",
    family: "laguna",
    context: 256_000,
    input: 0,
    output: 0,
    cacheRead: 0,
    cacheWrite: 0,
  },
  {
    id: "meituan/LongCat-2.0:free",
    name: "LongCat 2.0",
    family: "longcat",
    context: 1_000_000,
    input: 0,
    output: 0,
    cacheRead: 0,
    cacheWrite: 0,
  },
  {
    id: "tencent/hy4-preview",
    name: "Tencent Hy4 Preview",
    family: "tencent",
    context: 1_000_000,
    input: 0.834,
    output: 2.501,
    cacheRead: 0.042,
    cacheWrite: 0,
  },
  {
    id: "tencent/hy3-paid",
    name: "Tencent Hy3",
    family: "tencent",
    context: 262_000,
    input: 0.14,
    output: 0.58,
    cacheRead: 0.035,
    cacheWrite: 0,
  },
  {
    id: "moonshotai/Kimi-K3",
    name: "Kimi K3",
    family: "kimi",
    context: 1_000_000,
    input: 3,
    output: 15,
    cacheRead: 0.3,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "moonshotai/Kimi-K2.7-Code",
    name: "Kimi K2.7 Code",
    family: "kimi",
    context: 256_000,
    input: 0.95,
    output: 4,
    cacheRead: 0.19,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "moonshotai/Kimi-K2.7-Code-Highspeed",
    name: "Kimi K2.7 Code HighSpeed",
    family: "kimi",
    context: 262_000,
    input: 1.9,
    output: 8,
    cacheRead: 0.38,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    family: "kimi",
    context: 256_000,
    input: 0.95,
    output: 4,
    cacheRead: 0.16,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    family: "kimi",
    context: 256_000,
    input: 0.6,
    output: 3,
    cacheRead: 0.1,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "z-ai/glm-5.3-flash",
    name: "GLM-5.3 Flash",
    family: "glm",
    context: 1_000_000,
    input: 0.15,
    output: 0.5,
    cacheRead: 0.03,
    cacheWrite: 0,
  },
  {
    id: "zai-org/GLM-5.3",
    name: "GLM-5.3",
    family: "glm",
    context: 1_000_000,
    input: 1.4,
    output: 4.4,
    cacheRead: 0.26,
    cacheWrite: 0,
  },
  {
    id: "zai-org/GLM-5.2",
    name: "GLM-5.2",
    family: "glm",
    context: 1_000_000,
    input: 1.4,
    output: 4.4,
    cacheRead: 0.26,
    cacheWrite: 0,
  },
  {
    id: "zai-org/GLM-5.2-Fast",
    name: "GLM-5.2 Fast",
    family: "glm",
    context: 1_000_000,
    input: 3,
    output: 10.25,
    cacheRead: 0.5,
    cacheWrite: 0,
  },
  {
    id: "zai-org/GLM-5.1",
    name: "GLM-5.1",
    family: "glm",
    context: 200_000,
    input: 1.4,
    output: 4.4,
    cacheRead: 0.26,
    cacheWrite: 0,
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    family: "glm",
    context: 200_000,
    input: 1,
    output: 3.2,
    cacheRead: 0.2,
    cacheWrite: 0,
  },
  {
    id: "MiniMaxAI/MiniMax-M3",
    name: "MiniMax M3",
    family: "minimax",
    context: 1_000_000,
    input: 0.3,
    output: 1.2,
    cacheRead: 0.06,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "MiniMaxAI/MiniMax-M2.7",
    name: "MiniMax M2.7",
    family: "minimax",
    context: 200_000,
    input: 0.3,
    output: 1.2,
    cacheRead: 0.06,
    cacheWrite: 0,
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax M2.5",
    family: "minimax",
    context: 200_000,
    input: 0.3,
    output: 1.2,
    cacheRead: 0.03,
    cacheWrite: 0,
  },
  {
    id: "deepseek/deepseek-v4-pro",
    name: "DeepSeek V4 Pro (latest)",
    family: "deepseek",
    context: 1_000_000,
    input: 0.66,
    output: 1.98,
    cacheRead: 0.022,
    cacheWrite: 0,
  },
  {
    id: "deepseek/deepseek-v4-flash",
    name: "DeepSeek V4 Flash (latest)",
    family: "deepseek",
    context: 1_000_000,
    input: 0.22,
    output: 0.66,
    cacheRead: 0.007,
    cacheWrite: 0,
  },
  {
    id: "deepseek/deepseek-v4-flash-vision-exp",
    name: "DeepSeek V4 Flash Vision (exp)",
    family: "deepseek",
    context: 1_000_000,
    input: 0.22,
    output: 0.66,
    cacheRead: 0.007,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "deepseek/deepseek-v4-flash-fast",
    name: "DeepSeek V4 Flash Fast",
    family: "deepseek",
    context: 1_000_000,
    input: 0.28,
    output: 0.56,
    cacheRead: 0.07,
    cacheWrite: 0,
  },
  {
    id: "Qwen/Qwen3.8-Max-0902",
    name: "Qwen 3.8 Max 0902",
    family: "qwen",
    context: 1_000_000,
    input: 2,
    output: 6,
    cacheRead: 0.25,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "Qwen/Qwen3.8-Max",
    name: "Qwen 3.8 Max",
    family: "qwen",
    context: 1_000_000,
    input: 2,
    output: 6,
    cacheRead: 0.25,
    cacheWrite: 2.5,
    image: true,
  },
  {
    id: "Qwen/Qwen3.8-27B",
    name: "Qwen 3.8 27B",
    family: "qwen",
    context: 262_000,
    input: 0.4,
    output: 3,
    cacheRead: 0.04,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "Qwen/Qwen3.6-Max-Preview",
    name: "Qwen 3.6 Max Preview",
    family: "qwen",
    context: 200_000,
    input: 1.3,
    output: 7.8,
    cacheRead: 0.26,
    cacheWrite: 1.63,
  },
  {
    id: "Qwen/Qwen3.6-Plus",
    name: "Qwen 3.6 Plus",
    family: "qwen",
    context: 200_000,
    input: 0.5,
    output: 3,
    cacheRead: 0.1,
    cacheWrite: 0,
  },
  {
    id: "Qwen/Qwen3.7-Max",
    name: "Qwen 3.7 Max",
    family: "qwen",
    context: 1_000_000,
    input: 2.5,
    output: 7.5,
    cacheRead: 0.5,
    cacheWrite: 3.13,
  },
  {
    id: "Qwen/Qwen3.7-Plus",
    name: "Qwen 3.7 Plus",
    family: "qwen",
    context: 1_000_000,
    input: 0.4,
    output: 1.6,
    cacheRead: 0.08,
    cacheWrite: 0.5,
  },
  {
    id: "Qwen/Qwen3.8-Flash",
    name: "Qwen 3.8 Flash",
    family: "qwen",
    context: 1_000_000,
    input: 0.16,
    output: 0.47,
    cacheRead: 0.016,
    cacheWrite: 0,
  },
  {
    id: "Qwen/Qwen3.7-Flash",
    name: "Qwen 3.7 Flash",
    family: "qwen",
    context: 1_000_000,
    input: 0.03,
    output: 0.13,
    cacheRead: 0.006,
    cacheWrite: 0.038,
  },
  {
    id: "stepfun/Step-3.7-Flash",
    name: "Step 3.7 Flash",
    family: "step",
    context: 256_000,
    input: 0.2,
    output: 1.15,
    cacheRead: 0.04,
    cacheWrite: 0,
  },
  {
    id: "stepfun/Step-3.5-Flash",
    name: "Step 3.5 Flash",
    family: "step",
    context: 1_000_000,
    input: 0.1,
    output: 0.3,
    cacheRead: 0.02,
    cacheWrite: 0,
  },
  {
    id: "xiaomi/mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    family: "mimo",
    context: 1_000_000,
    input: 0.435,
    output: 0.87,
    cacheRead: 0.0036,
    cacheWrite: 0,
  },
  {
    id: "xiaomi/mimo-v2.5",
    name: "MiMo V2.5",
    family: "mimo",
    context: 1_000_000,
    input: 0.14,
    output: 0.28,
    cacheRead: 0.0028,
    cacheWrite: 0,
  },
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b",
    name: "Nemotron 3 Ultra",
    family: "nemotron",
    context: 1_000_000,
    input: 0.6,
    output: 2.4,
    cacheRead: 0.12,
    cacheWrite: 0,
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    family: "gpt",
    context: 1_100_000,
    input: 0.2,
    output: 1.2,
    cacheRead: 0.02,
    cacheWrite: 0.25,
  },
  {
    id: "meta/muse-spark-1.3-contributor",
    name: "Muse Spark 1.3 Contributor",
    family: "muse",
    context: 1_000_000,
    input: 0.1,
    output: 0.2,
    cacheRead: 0.002,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "meta/muse-spark-1.2-contributor",
    name: "Muse Spark 1.2 Contributor",
    family: "muse",
    context: 1_000_000,
    input: 0.1,
    output: 0.2,
    cacheRead: 0.002,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "xai/grok-4.5",
    name: "Grok 4.5",
    family: "grok",
    context: 500_000,
    input: 2,
    output: 6,
    cacheRead: 0.5,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "thinkingmachines/inkling",
    name: "Inkling",
    family: "inkling",
    context: 256_000,
    input: 1,
    output: 4.05,
    cacheRead: 0.17,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "thinkingmachines/inkling-small",
    name: "Inkling Small",
    family: "inkling",
    context: 1_000_000,
    input: 0.5,
    output: 1.2,
    cacheRead: 0.1,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "google/gemini-3.8-flash",
    name: "Gemini 3.8 Flash",
    family: "gemini",
    context: 1_000_000,
    input: 1.5,
    output: 7.5,
    cacheRead: 0.15,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "google/gemini-3.7-flash",
    name: "Gemini 3.7 Flash",
    family: "gemini",
    context: 1_000_000,
    input: 1.5,
    output: 7.5,
    cacheRead: 0.15,
    cacheWrite: 0.08334,
    image: true,
  },
  {
    id: "meta/muse-spark-1.3",
    name: "Muse Spark 1.3",
    family: "muse",
    context: 1_000_000,
    input: 1.25,
    output: 4.25,
    cacheRead: 0.15,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "meta/muse-spark-1.2",
    name: "Muse Spark 1.2",
    family: "muse",
    context: 1_000_000,
    input: 1.25,
    output: 4.25,
    cacheRead: 0.15,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "meta/muse-spark-1.1",
    name: "Muse Spark 1.1",
    family: "muse",
    context: 1_000_000,
    input: 1.25,
    output: 4.25,
    cacheRead: 0.15,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "google/gemini-3.5-flash-lite",
    name: "Gemini 3.5 Flash Lite",
    family: "gemini",
    context: 1_000_000,
    input: 0.3,
    output: 2.5,
    cacheRead: 0.03,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "google/gemini-3.6-flash",
    name: "Gemini 3.6 Flash",
    family: "gemini",
    context: 1_000_000,
    input: 1.5,
    output: 7.5,
    cacheRead: 0.15,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "google/gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    family: "gemini",
    context: 1_000_000,
    input: 1.5,
    output: 9,
    cacheRead: 0.15,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "google/gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    family: "gemini",
    context: 1_000_000,
    input: 0.25,
    output: 1.5,
    cacheRead: 0.03,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    family: "gpt",
    context: 1_100_000,
    input: 5,
    output: 30,
    cacheRead: 0.5,
    cacheWrite: 6.25,
  },
  {
    id: "xai/grok-4.6",
    name: "Grok 4.6",
    family: "grok",
    context: 500_000,
    input: 2,
    output: 6,
    cacheRead: 0.5,
    cacheWrite: 0,
    image: true,
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    family: "gpt",
    context: 1_100_000,
    input: 2,
    output: 12,
    cacheRead: 0.2,
    cacheWrite: 2.5,
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    family: "claude",
    context: 1_000_000,
    input: 2,
    output: 10,
    cacheRead: 0.2,
    cacheWrite: 2.5,
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    family: "claude",
    context: 1_000_000,
    input: 3,
    output: 15,
    cacheRead: 0.3,
    cacheWrite: 3.75,
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    family: "gpt",
    context: 400_000,
    input: 5,
    output: 30,
    cacheRead: 0.5,
    cacheWrite: 0,
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    family: "gpt",
    context: 400_000,
    input: 0.75,
    output: 4.5,
    cacheRead: 0.075,
    cacheWrite: 0,
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    family: "gpt",
    context: 400_000,
    input: 2,
    output: 8,
    cacheRead: 0.5,
    cacheWrite: 0,
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    family: "gpt",
    context: 400_000,
    input: 2.5,
    output: 15,
    cacheRead: 0.25,
    cacheWrite: 0,
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5",
    family: "claude",
    context: 200_000,
    input: 1,
    output: 5,
    cacheRead: 0.1,
    cacheWrite: 1.25,
  },
]
